name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Change to GiftcardSite directory
      run: cd GiftcardSite

    - name: Grant execute permission for gradlew
      run: chmod +x ./gradlew
      working-directory: ./GiftcardSite

    - name: Build with Gradle
      run: ./gradlew build
      working-directory: ./GiftcardSite

    - name: Run tests
      run: ./gradlew test
      working-directory: ./GiftcardSite
